/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  Ciro
 * Created: May 25, 2016
 */



CREATE TABLE Compratore (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nome VARCHAR(128),
        cognome VARCHAR(128),
        username  VARCHAR(128),
        password VARCHAR(128)
);

CREATE TABLE Venditore (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nome VARCHAR(128),
        cognome VARCHAR(128),
        username  VARCHAR(128),
        password VARCHAR(128)
        
);

CREATE TABLE Oggetti (
        venditoreId INTEGER NOT NULL,
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        quantita INTEGER,
        nome VARCHAR(128),
        prezzo DOUBLE,
        url VARCHAR(128),
        descrizione VARCHAR(128),
        FOREIGN KEY (venditoreId) REFERENCES venditore(id)
);

CREATE TABLE Account (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        soldi DOUBLE
);

INSERT INTO Compratore (id, nome, cognome, username, password)
VALUES (default, 'Gigi', 'Mereu', 'Gimmy', 'aa'),
       (default, 'gabriele', 'piras', 'eldiablo', 'bb');

INSERT INTO Venditore (id, nome, cognome, username, password)
VALUES (default, 'Babbo', 'Natale', 'babbo', 'cc'),
       (default, 'Andrea', 'Casti', 'aereo', 'plano');

INSERT INTO Oggetti (id, venditoreId, nome, quantita, prezzo, url, descrizione)
VALUES (default, 1, 'Set di chips', 1, 149, 'Milestone3/web/img/chips.jpg', 'generico'),
       (default, 1, 'Donna dellest', 3, 0, '/img/donne.jpg', 'generico'),
       (default, 1, 'Mazzo di carte', 2, 349, '/img/cards.jpg', 'generico'),
       (default, 2, 'Tavolo da poker', 1, 399, '/img/tavolo.jpg', 'generico'),
       (default, 2, 'Pistola contro i bari', 6, 799, '/img/pistola.jpg', 'generico'),
       (default, 2, 'Slot machine', 4, 999, '/img/slot.jpg', 'generico');

INSERT INTO Account (id, soldi)
VALUES (default, 1500),
       (default, 120),
       (default, 15000),
       (default, 50);
